<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<style>
table {
    border-collapse: collapse;
    width: 100%;
    font-size: 14px;
    margin-top: 10px;
}

.left {
    float: left;
}

td.w-10 {
    width: 10%;
}

td.w-40 {
    width: 40%;
}

td.w-100 {
    width: 100%;
}

td.w-33 {
    width: 33%;
}

table,
td,
th {

    border: none;

}

th {
    font-weight: normal;
    text-align: center;
    padding: 5px 5px 0px 5px;
    background-repeat: repeat-x;
    height: 25px;
    font-size: 16px;
    font-weight: bold;
    border: 1px solid #000;
}

td {
    padding: 16px 3px 3px 3px;
    border: 1px solid #000;
}

.em-wide {
    letter-spacing: 1rem;
}
.letter {
    letter-spacing: 0.3rem;
}
.pic {
    height: 73px;
    width: 200px;
    float: right;
    margin: 0 15px 0 0;
    border-radius: 45%;
}
</style>

<body>
    <center>
        <h1 class="em-wide">Tomgu Square</h1>
    </center>
    <hr>
    <img class="pic" src="<?php echo base_url().'uploads/tomgu.jpg.jpg'?>">
    <p><b>Address:</b> Poblacion Madridejos Cebu</p>
    <p><b>Date:</b> <?php echo date("M. d, Y") ?></p>
    <hr>
    <center><h1 class="letter">Sales Report</h1></center>
    <table class="table table-bordered table-striped" id="report-field">
        <thead>
            <tr>
                <td class="text-center"><center>#</center></td>
                <td class="text-center"><center>Referrence #</center></td>
                <td class="text-center"><center>Date</center></td>
                <td class="text-center"><center>Amount</center></td>

            </tr>
        </thead>
        <tbody>
            <?php 
			$i =0 ;
			$order = $this->db->query("SELECT * FROM orders");
			$items = $this->db->query("SELECT * FROM sales ORDER BY `sales`.`ref_id` ASC");
            $product = $this->db->query("SELECT * FROM product");
				foreach($items->result_array() as $row):
					$i++;
			?>
            <tr>
                <td>
                    <center><b><?php echo $i ?></b></center>
                </td>
                <td><center><?php echo ($row['ref_id'])?></center></td>
                <td class="text-center"><center><?php echo  $row['date_created'] = date('M d, Y',strtotime($row['date_created']))?></center></td>
                <td class="text-center"><center><b>Php&nbsp;<?php echo number_format($row['total_amount'],2) ?></b></center></td>
            </tr>
            <?php endforeach; ?>
        </tbody>
        <tfoot>
            <?php
		$result = $this->db->query("SELECT sum(total_amount) FROM sales");
		foreach($result->result_array() as $row):
	?>
            <tr>
                <td colspan="3" align="right" class="text-left"><b>Total Sales:</b></td>
                <td class="text-right" colspan="3"><center><b>Php&nbsp;<?php echo number_format($row['sum(total_amount)'],2) ?></center></b></td>
            </tr>
            <?php endforeach; ?>
        </tfoot>
    </table>
    <br>
    <p><b>Generated by:</b> <?php echo $_SESSION['firstname']?> <?php echo $_SESSION['lastname'] ?></p>
</body>
</html>